AllCops:
  TargetRubyVersion: 3.1.2
  SuggestExtensions: false
  NewCops: enable
  DisplayCopNames: true
  Exclude:
    - "bin/**"
    - "db/schema.rb"
    - "db/migrate/**"
    - "vendor/**/*"
    - "node_modules/**/*"

Style/StringLiterals:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Layout/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false